# Generated by Django 5.2.7 on 2025-11-24 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='notes',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
