# Generated by Django 5.2.7 on 2025-11-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ordonnance_diagnostic_ordonnance_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='users.doctor'),
        ),
    ]
