# Generated by Django 5.2.7 on 2025-12-01 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_appointment_doctor_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='users.appointment'),
        ),
    ]
