# Generated by Django 5.2.7 on 2025-11-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_ordonnance_date_remove_ordonnance_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnances', to='users.patient'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='prescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
